### ISSUE TITLE
still active?

### ISSUE THREAD

**Issue by beckettsean** [raphaelthomas/InfluxDB-HTTP#1]
I'm cleaning up the https://docs.influxdata.com/influxdb/v1.0/tools/api_client_libraries/ page and removing those libraries that aren't compatible with InfluxDB 1.0. 

I'll remove this project from that page on October 15th unless you have plans to update for 1.0 compatibility. Thanks!

**Comment by raphaelthomas** [comment]
Hi Sean. Yes this project is still active and compatible with InfluxDB 1.0. We use it in production with InfluxDB 1.0.2 and haven't noticed any incompatibility.
