### ISSUE TITLE
Cannot use on centos

### ISSUE THREAD

**Issue by mpaul-ord** [raphaelthomas/InfluxDB-HTTP#3]
Hi,
I am a DBA trying to use influxDB::HTTP perl module on centos7.3

Downladed : 
$ wget https://github.com/raphaelthomas/InfluxDB-HTTP/archive/0.02.tar.gz

I compiled the .02 module but running the base code gives
"Can't locate Method/Signatures.pm in @INC "

So I did search 
cricket:/var/opt/work $ yum search Method::Signatures
======================================== Matched: Method::Signatures =========================================
perl-Parse-Method-Signatures.noarch : Perl6 like method signature parser

$ yum install perl-Parse-Method-Signatures.noarch

and installed that ..  but  still  get 
perl -c connect_influxdb
Can't locate Method/Signatures.pm in @INC 

.. What am I doing wrong!

Any help is appreciated.

Thanks.
MPAUL

**Comment by agoetschm** [comment]
I guess #5 solves that
